import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {/* <nav className="py-5 px-4 bg-red-500 font-bold">
          <div>
            <Link href={'/'} className="text-white">
              My Project Page cdsfafs 시발
            </Link>
          </div>

          <div className="float-right">
            <Link href="/team_project" className="menu_item">
              팀 프로젝트
            </Link>
            <Link href="/" className="menu_item">
              개인 프로젝트
            </Link>

            <Link href="/" className="menu_item">
              프로필
            </Link>
          </div>
        </nav> */}

        <div className="container">{children}</div>
      </body>
    </html>
  )
}
